apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: envoy
spec:
  interval: 5m
  type: oci
  url: oci://docker.io/envoyproxy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gatweway
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: gateway-helm
      version: "1.6.0"
      sourceRef:
        kind: HelmRepository
        name: envoy
      interval: 5m
  releaseName: envoy-gateway
