apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-envoy-client
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: dex-envoy-client
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        client-secret: "{{ .pw }}"
  data:
    - secretKey: pw
      remoteRef:
        key: dex-envoy-client-secret
        version: CURRENT
        decodingStrategy: None
