apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-envoy-client
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: dex-envoy-client
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        client-secret: "{{ .pw }}"
  data:
    - secretKey: pw
      remoteRef:
        key: dex-envoy-client-secret
        version: CURRENT
        decodingStrategy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-slack-webhook
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: alertmanager-slack-webhook
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        url: "{{ .url }}"
  data:
    - secretKey: url
      remoteRef:
        key: SLACK_API_URL
        version: CURRENT
        decodingStrategy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prometheus-remote-write-basic-auth
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: prometheus-remote-write-basic-auth
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        ".htpasswd": "{{ .htpasswd }}"
  data:
    - secretKey: htpasswd
      remoteRef:
        key: prometheus-remote-write-htpasswd
        version: CURRENT
        decodingStrategy: None
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: prometheus-remote-write-basic-auth
spec:
  length: 40
  digits: 8
  symbols: 0
  allowRepeat: true
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: prometheus-remote-write-basic-auth
spec:
  refreshInterval: 3m
  updatePolicy: Replace
  deletionPolicy: None
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: oracle-vault
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: prometheus-remote-write-basic-auth
  template:
    engineVersion: v2
    data:
      username: prometheus
      password: "{{ .password }}"
      ".htpasswd": '{{ htpasswd "prometheus" .password "bcrypt" }}'
  data:
    - match:
        secretKey: ".htpasswd"
        remoteRef:
          remoteKey: prometheus-remote-write-htpasswd
    - match:
        secretKey: username
        remoteRef:
          remoteKey: prometheus-remote-write-username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: prometheus-remote-write-password
