---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: default
spec:
  interval: 10m
  timeout: 5m
  targetNamespace: external-secrets
  chart:
    spec:
      chart: external-secrets
      version: '0.9.13'
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      interval: 5m
  releaseName: external-secrets
