apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-github-connector
  namespace: dex
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: home-vault
  target:
    name: dex-github-connector
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: GITHUB_CLIENT_ID
      remoteRef:
        key: GITHUB_DEX_CLIENT_ID
        version: CURRENT
        decodingStrategy: None
    - secretKey: GITHUB_CLIENT_SECRET
      remoteRef:
        key: GITHUB_DEX_CLIENT_SECRET
        version: CURRENT
        decodingStrategy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-grafana-client
  namespace: dex
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: home-vault
  target:
    name: dex-grafana-client
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        grafana.client-id: grafana
        grafana.client-secret: "{{ .pw }}"
  data:
    - secretKey: pw
      remoteRef:
        key: dex-grafana-client
        version: CURRENT
        decodingStrategy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-s3-proxy-client
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: home-vault
  target:
    name: dex-s3-proxy-client
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        s3proxy.client-id: s3-proxy
        s3proxy.client-secret: "{{ .pw }}"
  data:
    - secretKey: pw
      remoteRef:
        key: dex-s3-proxy-client-secret
        version: CURRENT
        decodingStrategy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-freshrss-client
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: home-vault
  target:
    name: dex-freshrss-client
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        freshrss.client-id: freshrss
        freshrss.client-secret: "{{ .pw }}"
  data:
    - secretKey: pw
      remoteRef:
        key: dex-freshrss-client
        version: CURRENT
        decodingStrategy: None