apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: teleport
  namespace: flux-system
spec:
  interval: 1h
  path: ./gitops/core/teleport
  prune: true
  dependsOn:
    - name: external-dns
    - name: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: teleport-rbac
  namespace: flux-system
spec:
  interval: 1h
  path: ./gitops/core/teleport/rbac/
  prune: true
  dependsOn:
    - name: teleport
  sourceRef:
    kind: GitRepository
    name: flux-system
