apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: teleport
  namespace: teleport
spec:
  interval: 5m
  url: https://charts.releases.teleport.dev
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teleport-cluster
  namespace: teleport
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: teleport-cluster
      version: "17.4.7"
      sourceRef:
        kind: HelmRepository
        name: teleport
      interval: 5m
  releaseName: teleport-cluster
  valuesFrom:
    - kind: ConfigMap
      name: oci-nlb-sg-id
      valuesKey: values.yaml
  values:
    chartMode: standalone
    clusterName: teleport.nce.wtf
    kubeClusterName: oci
    proxyListenerMode: multiplex
    auth:
      teleportConfig:
        auth_service:
          authentication:
            type: github
    authentication:
      type: github
      localAuth: true
      secondFactor: on
    highAvailability:
      replicaCount: 1
      certManager:
        enabled: true
        issuerName: letsencrypt
        issuerKind: ClusterIssuer
    operator:
      enabled: true
    ingress:
      enabled: false
    proxy:
      highAvailability:
        replicaCount: 1
      service:
        type: LoadBalancer
      annotations:
        service:
          external-dns.alpha.kubernetes.io/hostname: teleport.nce.wtf
          oci.oraclecloud.com/load-balancer-type: "nlb"
          oci-network-load-balancer.oraclecloud.com/oci-network-security-groups: "ocid1.networksecuritygroup.oc1.eu-frankfurt-1.aaaaaaaauxhghg36xuzzjgw2awsd3cv4p2f2jedr5palq6fpy4exd53tve5a"
