apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: teleport-github-connector
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: home-vault
  target:
    name: teleport-github-connector
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      metadata:
        annotations:
          resources.teleport.dev/allow-lookup-from-cr: "*"
  data:
    - secretKey: teleport-github-client-secret
      remoteRef:
        key: teleport-github-client-secret
        version: CURRENT
        decodingStrategy: None
