apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: freshrss
  namespace: flux-system
spec:
  interval: 1h
  path: ./gitops/core/freshrss
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: freshrss
      namespace: freshrss
