# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: freshrss
  namespace: freshrss
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.4.0
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: freshrss
spec:
  chartRef:
    kind: OCIRepository
    name: freshrss
  interval: 30m
  values:
    controllers:
      freshrss:
        containers:
          app:
            image:
              repository: docker.io/freshrss/freshrss
              tag: 1.27.1
            env:
              CRON_MIN: "*"
              DOMAIN: rss.jdani.eu
              LISTEN: &port 8080
              OIDC_ENABLED: 1
              OIDC_PROVIDER_METADATA_URL: https://login.jdani.eu/dex/.well-known/openid-configuration
              OIDC_REDIRECT_URI: https://rss.jdani.eu/i/oidc/
              OIDC_REMOTE_USER_CLAIM: preferred_username
              OIDC_SCOPES: openid email profile
              OIDC_X_FORWARDED_HEADERS: X-Forwarded-Host X-Forwarded-Port X-Forwarded-Proto
              
            envFrom:
              - secretRef:
                  name: dex-freshrss-client
              - secretRef:
                  name: freshrss-oidc-crypto-key

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 12m
                memory: 128M
              limits:
                memory: 512M
    service:
      app:
        ports:
          http:
            port: *port
    persistence:
      data:
        existingClaim: freshrss-data
        advancedMounts:
          freshrss:
            app:
              - path: /var/www/FreshRSS/data
                subPath: data
                readOnly: false
              - path: /var/www/FreshRSS/extensions
                subPath: extensions
                readOnly: false
    # route:
    #   app:
    #     hostnames:
    #       - rss.jdani.eu