---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-freshrss-client
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: home-vault
  target:
    name: dex-freshrss-client
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        OIDC_CLIENT_ID: freshrss
        OIDC_CLIENT_SECRET: "{{ .pw }}"
  data:
    - secretKey: pw
      remoteRef:
        key: dex-freshrss-client
        version: CURRENT
        decodingStrategy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: freshrss-oidc-crypto-key
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: home-vault
  target:
    name: freshrss-oidc-crypto-key
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: OIDC_CLIENT_CRYPTO_KEY
      remoteRef:
        key: freshrss-oidc-crypto-key
        version: CURRENT
        decodingStrategy: None
