apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 10m
  timeout: 5m
  targetNamespace: longhorn-system
  chart:
    spec:
      chart: longhorn
      version: '1.8.1'
      sourceRef:
        kind: HelmRepository
        name: longhorn
      interval: 5m
  releaseName: longhorn
  values:
    defaultSettings:
      storageMinimalAvailablePercentage: 10
    persistence:
      defaultClassReplicaCount: 2
    ingress:
      enabled: true
      tls: true
      host: storage.klangregen.de
      tlsSecret: longhorn-cert
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        acme.cert-manager.io/http01-edit-in-place: "true"
        kubernetes.io/ingress.class: nginx
        external-dns.alpha.kubernetes.io/hostname: storage.klangregen.de
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: basic-auth
        nginx.ingress.kubernetes.io/auth-realm: "Enter your credentials"
