apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
spec:
  interval: 5m
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: longhorn
      version: '1.9.0'
      sourceRef:
        kind: HelmRepository
        name: longhorn
      interval: 5m
  releaseName: longhorn
  values:
    defaultSettings:
      storageMinimalAvailablePercentage: 10
    persistence:
      defaultClassReplicaCount: 2
    ingress:
      enabled: true
      tls: true
      host: storage.nce.wtf
      tlsSecret: longhorn-cert
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        kubernetes.io/ingress.class: nginx
        external-dns.alpha.kubernetes.io/hostname: storage.nce.wtf
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: basic-auth
        nginx.ingress.kubernetes.io/auth-realm: "Enter your credentials"
