apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
spec:
  interval: 5m
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: longhorn
      version: '1.10.0'
      sourceRef:
        kind: HelmRepository
        name: longhorn
      interval: 5m
  releaseName: longhorn
  values:
    defaultSettings:
      storageMinimalAvailablePercentage: 10
    persistence:
      defaultClassReplicaCount: 2
    ingress:
      enabled: false
