apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
spec:
  interval: 5m
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: longhorn
      version: '1.10.0'
      sourceRef:
        kind: HelmRepository
        name: longhorn
      interval: 5m
  releaseName: longhorn
  values:
    image:
      csi:
        attacher:
          registry: docker.io
        livenessProbe:
          registry: docker.io
        nodeDriverRegistrar:
          registry: docker.io
        provisioner:
          registry: docker.io
        resizer:
          registry: docker.io
        snapshotter:
          registry: docker.io
      longhorn:
        backingImageManager:
          registry: docker.io
        engine:
          registry: docker.io
        instanceManager:
          registry: docker.io
        manager:
          registry: docker.io
        shareManager:
          registry: docker.io
        supportBundleKit:
          registry: docker.io
        ui:
          registry: docker.io  
      openshift:
        oauthProxy:
          registry: docker.io
    defaultSettings:
      storageMinimalAvailablePercentage: '10'
    persistence:
      defaultClassReplicaCount: 2
    ingress:
      enabled: true
      tls: true
      host: storage.jdani.eu
      tlsSecret: longhorn-cert
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        kubernetes.io/ingress.class: nginx
        external-dns.alpha.kubernetes.io/hostname: storage.jdani.eu
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: basic-auth
        nginx.ingress.kubernetes.io/auth-realm: "Enter your credentials"
