apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 5m
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 10m
  timeout: 5m
  targetNamespace: external-secrets
  chart:
    spec:
      chart: external-secrets
      version: '0.10.4'
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      interval: 5m
  releaseName: external-secrets
