apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-addons
  namespace: flux-system
spec:
  interval: 1h
  path: ./gitops/core/fluxcd-addons
  prune: true
  dependsOn:
    - name: external-secrets
    - name: ingress-nginx
  sourceRef:
    kind: GitRepository
    name: flux-system
