{
 "title": "Balkonkraftwerk",
 "tags": [ "bkw" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Watt",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "watt", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Watt",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "watt", "legendFormat": "Watt (WEB)" },
    {
     "expr": "sum ((current{} * voltage{}) > 0) < 900",
     "legendFormat": "Watt (Modbus)"
    }
   ]
  },
  {
   "title": "Online",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 1 },
   "targets": [
    { "expr": "online", "legendFormat": "online" }
   ]
  },
  {
   "title": "Tagesleistung",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "today_e", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Leistung Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_e", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Spannung",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "(voltage > -1) <100", "legendFormat": "Panel {{panel}}" }
   ]
  },
  {
   "title": "Strom",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "current > -1 < 100", "legendFormat": "Panel {{panel}}" }
   ]
  },
  {
   "title": "Watt",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "(current{} * voltage{}) > 0 <2000",
     "legendFormat": "Panel {{panel}}"
    }
   ]
  },
  {
   "title": "Amortisierung",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_e*0.36" }
   ]
  },
  {
   "title": "Abfragezeit",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    { "expr": "executiontime", "legendFormat": "Zeit" }
   ]
  },
  {
   "title": "Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "temperature != (-10.00)", "legendFormat": "Temperatur" }
   ]
  },
  {
   "title": "Aktueller Monat",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "max_over_time(today_e{job=\"solar_exporter\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Letzte 7 Tage",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "max_over_time(today_e{job=\"solar_exporter\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Summe der letzten 10 Tage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(today_e{job=\"solar_exporter\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Letzter Monat",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "max_over_time(today_e[$__interval])"
    }
   ]
  }
 ]
}