apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: s3-proxy
  namespace: flux-system
spec:
  interval: 1h
  path: ./gitops/core/s3-proxy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: s3-proxy
      namespace: s3-proxy
