apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: evolution-api-postgresql
  namespace: evolution-api
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: evolution-api

  storage:
    size: 5Gi
    storageClass: longhorn

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  postgresql:
    parameters:
      max_connections: "30"
      shared_buffers: "128MB"
      effective_cache_size: "512MB"
      work_mem: "4MB"
      maintenance_work_mem: "64MB"
      wal_buffers: "4MB"
      checkpoint_completion_target: "0.9"
      random_page_cost: "1.1"
      default_statistics_target: "100"


  logLevel: warning
