apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: evolution-api
    app.kubernetes.io/name: evolution-api
  name: evolution-api-data
  namespace: evolution-api
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn