apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: evolution-api-global-key
  namespace: evolution-api
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: home-vault
  target:
    name: evolution-api-global-key
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data: 
        AUTHENTICATION_API_KEY: "{{ .api_key }}"
  data:
    - secretKey: api_key
      remoteRef:
        key: evolution-api-global-key
        version: CURRENT
