apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: 8gears-n8n
  namespace: n8n
spec:
  interval: 5m0s
  url: oci://8gears.container-registry.com/library/n8n
  ref:
    tag: 1.1.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  driftDetection:
    mode: enabled
  interval: 10m
  releaseName: n8n
  chartRef:
    kind: OCIRepository
    name: 8gears-n8n
  values:
    image:
      repository: docker.io/n8nio/n8n
      pullPolicy: IfNotPresent
    main:    
      config:
        database:
          type: sqlite

      extraEnv:
        WEBHOOK_URL:
          value: "https://n8n-webhooks.jdani.eu"
        N8N_PROXY_HOPS:
          value: "1"
        N8N_HOST:
          value: "n8n.jdani.eu"
        GENERIC_TIMEZONE:
          value: "Europe/Madrid"
        N8N_EDITOR_BASE_URL:
          value: "https://n8n.jdani.eu"
        DB_SQLITE_POOL_SIZE:
          value: "5"
        N8N_RUNNERS_ENABLED:
          value: "true"
        N8N_BLOCK_ENV_ACCESS_IN_NODES:
          value: "true"
        N8N_GIT_NODE_DISABLE_BARE_REPOS:
          value: "true"

      persistence:
        enabled: true
        type: dynamic
        existingClaim: n8n-data



      podAnnotations: { }

      service:
        type: ClusterIP
        port: 8080
        annotations: { }

    webhook:
      enabled: false

    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/hostname: n8n.jdani.eu
      hosts:
        - host: n8n.jdani.eu
          paths:
          - /
      tls:
      - secretName: n8n-https-cert
        hosts:
          - n8n.jdani.eu