apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secrets
  namespace: external-dns
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: home-vault
  target:
    name: external-dns-config
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        apiKey: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: cloudflare-api-token
        version: CURRENT
