---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secrets
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: external-dns-config
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        oci.yaml: |
          compartment: {{ .compartment }}
          auth:
            region: eu-frankfurt-1
            tenancy: {{ .compartment }}
            user: {{ .user }}
            fingerprint: {{ .fingerprint }}
            key: |
              {{ .private_key | trim }}
  data:
  - secretKey: user
    remoteRef:
      key: oci-external-dns-user
      version: CURRENT
      decodingStrategy: None
  - secretKey: private_key
    remoteRef:
      key: oct-external-dns-api-key
      version: CURRENT
      decodingStrategy: None
  - secretKey: user
    remoteRef:
      key: oci-external-dns-user
      version: CURRENT
      decodingStrategy: None
  - secretKey: fingerprint
    remoteRef:
      key: oci-external-dns-api-key-fingerprint
      version: CURRENT
      decodingStrategy: None
  - secretKey: compartment
    remoteRef:
      key: oci-tenancy
      version: CURRENT
      decodingStrategy: None
