apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
spec:
  interval: 5m
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.12.1"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      interval: 5m
  releaseName: ingress-nginx
  valuesFrom:
    - kind: ConfigMap
      name: oci-lb-sg-id
      valuesKey: values.yaml
  values:
    controller:
      allowSnippetAnnotations: true
      config:
        limit-rate: "1048576"
        limit-rate-after: "5242880"
        proxy-buffering: "on"
      replicaCount: 2
      service:
        annotations:
          service.beta.kubernetes.io/oci-load-balancer-shape: flexible
          service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
          service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "10"
          oci.oraclecloud.com/oci-network-security-groups: "{{ tpl .Values.oci.lbsecuritygroup . }}"
        externalTrafficPolicy: "Local"
        nodePorts:
          https: "30443"
          http: "30080"
