apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 10m
  timeout: 5m
  targetNamespace: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: "4.12.1"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      interval: 5m
  releaseName: ingress-nginx
  valuesFrom:
    - kind: ConfigMap
      name: oci-nlb-sg-id
      valuesKey: values.yaml
  values:
    controller:
      config:
        proxy-buffering: "on"
      replicaCount: 2
      service:
        annotations:
          oci.oraclecloud.com/load-balancer-type: "nlb"
          oci-network-load-balancer.oraclecloud.com/oci-network-security-groups: "{{ tpl .Values.oci.nlbsecuritygroup . }}"
        externalTrafficPolicy: "Local"
        nodePorts:
          https: "30443"
          http: "30080"
