apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../core/external-secrets/
  - ../../core/external-dns/
  - ../../core/cert-manager/
  - ../../core/cert-manager/issuer/
  - ../../core/dex/
  - ../../core/grafana/
  - ../../core/longhorn/
  - ../../core/lychee/
  - ../../core/kube-prometheus-stack/
  - ../../core/teleport/
  - ../../core/ingress-nginx/
  - ../../core/metrics-server/
  - ../../core/fluxcd-addons/
