apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuer
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
    - name: external-secrets
  interval: 5m
  path: "./gitops/core/cert-manager/issuer"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
