apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api
  namespace: cert-manager
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        api-token: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: cloudflare-api-token
        version: CURRENT
